### ISSUE TITLE
Integration for Firefox/Chrome?

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [polygonplanet/chillout#1]
Any way you could provide a packed-script for integration into Chrome/Firefox via https://tampermonkey.net/ for example?

**Comment by polygonplanet** [comment]
Do you want to using the chillout.js in userscript?

**Comment by Unrepentant-Atheist** [comment]
Yes, for example with userscript or tampermonkey.

**Comment by polygonplanet** [comment]
Currently, because the chillout.js is not provide on CDN, `@require` does not work.
You can embed `chillout.js` or `chillout.min.js` source code directly to your userscript. or any way?
I've tested it and it works on Chrome/Firefox Tampermonkey.
