### ISSUE TITLE
Benchmarks sanity

### ISSUE THREAD

**Issue by YurySolovyov** [polygonplanet/chillout#2]
In most modern js VMs this loop should be eliminated into dead code.
My guess is that you need to somehow use the result or do some side-effect to make this bench more realistic. 
```js
function heavyProcess() {
  for (var i = 0; i < 10000; i++) {
    for (var j = 0; j < 10000; j++) {
      var v = i*j;
    }
  }
}
```

**Comment by YuriSolovyov** [comment]
I was [partially right](https://twitter.com/mraleph/status/742730904892809216)

**Comment by polygonplanet** [comment]
I've checked the [intermediate representation](https://gist.github.com/polygonplanet/f5e079107b836ee4877d19a87cde9eb7/bdcb4637b9bfa683fa936989ed2afdd3905b44fe) of the `heavyProcess` that V8’s optimizing compiler generates, and found that the multiply expression has not been executed.
But the loops are executed the specified number of times, so it will not affected to this benchmark that is for the CPU load. but it should be corrected for different from the actual process and the test code.

[I've able to prevent the optimization](https://gist.github.com/polygonplanet/f5e079107b836ee4877d19a87cde9eb7/revisions#diff-74ecdc7f9c7e9d4164719bf4972b9b73R112) by put the [return statement](https://gist.github.com/polygonplanet/f5e079107b836ee4877d19a87cde9eb7/revisions#diff-fc40cdef7c488516fd869e42c64f4be4R8) in the function.
