### ISSUE TITLE
sometimes chillout.StopIteration can not break chillout.waitUntil

### ISSUE THREAD

**Issue by xjfnet** [polygonplanet/chillout#20]
```js
await chillout.waitUntil(function () {
    var length = $('...').length;
    console.log(length); // 1
    if (!!length) {
        return chillout.StopIteration;
    }
});
```
chrome browser
the waitUntil fall in endless loop, then open dev tools, i see the 1 growing
keep the dev tools, refresh the page, the code work fine, the waitUntil success

**Comment by polygonplanet** [comment]
@xjfnet I tried to run your code with jQuery, but it didn't occur the endless loop.

```js
const div = document.createElement('div');
div.id = 'test';
document.body.appendChild(div);

(async () => {
  await chillout.waitUntil(function () {
    var length = $('#test').length;
    console.log(length); // 1
    if (!!length) {
      console.log('stop');
      return chillout.StopIteration;
    }
    console.log('waiting');
  });
})();
```
console output:
> 1
> stop

jQuery v3.5.1
chillout v5.0.05
(Google Chrome 85.0.4183.121 64bit)

Maybe the `var length = $('...').length` part of it has returned 0. Or do you have running other chillout loops in parallel?
If you have any other code examples of this case, please comment.

**Comment by polygonplanet** [comment]
We will close this issue for now.
