### ISSUE TITLE
Interesting project, but how do you detect the CPU usage and choose the right way to run the code?

### ISSUE THREAD

**Issue by hz0324** [polygonplanet/chillout#6]

**Comment by polygonplanet** [comment]
The benchmark code is [`test/benchmark.js`](https://github.com/polygonplanet/chillout/blob/master/test/benchmark.js) and you can try the benchmark by `npm run benchmark`.
But it is difficult to get CPU usage accurately percent in the node.
Sometime it does not work well on Windows, if you can not get the CPU usage, try several times.
